steps:
  - script: |
      echo "=== Set SSH keypair ==="
      mkdir -p ~/.ssh
      echo -e "$(hana-pipeline-rsa)" > ~/.ssh/id_rsa
      echo -e "$(hana-pipeline-rsa-pub)" > ~/.ssh/id_rsa.pub
      chmod 400 ~/.ssh/id_rsa
      git checkout $(sourceBranchName)

      echo "=== Get agent IP ==="
      echo '##vso[task.setvariable variable=agent_ip]$(curl -s https://ipinfo.io/json | jq -r .ip)'
    displayName: "Pre deployment"
