trigger: none
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - deploy/terraform/bootstrap/sap_deployer
    - deploy/terraform/run/sap_deployer
    - deploy/terraform/terraform-units/modules/sap_deployer
variables:
  - group: azure-config-variables
  - group: azure-sap-hana-pipeline-secrets
  - template: templates/variables.yaml
stages:
- stage:
  pool:
    vmImage: "ubuntu-18.04"
  jobs:
  - job: createDeployer
    steps:
      - template: templates/pre-deployment-steps.yml
      - template: templates/deployer/create-deployer-steps.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer-$(Build.BuildId)"
      - template: templates/deployer/delete-deployer-steps.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer-$(Build.BuildId)"
