trigger: none
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - deploy/terraform/run/sap_system
    - deploy/terraform/terraform-units/modules/sap_system
variables:
  - group: azure-config-variables
  - group: azure-sap-hana-pipeline-secrets
  - template: templates/variables.yaml
stages:
- stage:
  pool:
    vmImage: "ubuntu-18.04"
  variables:
    ssh_timeout_s: 120
  jobs:
  - job: createSAPSystem
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
      - template: templates/sapsystem/create-sapsystem-steps.yml
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
  - job: deleteSAPSystem
    dependsOn: createSAPSystem
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
      - template: templates/sapsystem/delete-sapsystem-steps.yml
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_rg_name: "ad-sap-deployer"
  - job: cleanUp
    dependsOn: deleteSAPSystem
    condition: or(succeededOrFailed(), always())
    steps:
      - script: |
          echo "=== Mark and try to delete rg  ==="
          az login --service-principal --user $(hana-pipeline-spn-id) --password $(hana-pipeline-spn-pw) --tenant $(landscape-tenant) --output none
          
          rg="ad-sap-system-$(Build.BuildId)"
          az group update --resource-group $rg --set tags.Delete=True
          az group delete -n $rg --no-wait -y

          exit 0
        displayName: "Cleanup"
        env:
          ARM_CLIENT_ID: $(hana-pipeline-spn-id)
          ARM_CLIENT_SECRET: $(hana-pipeline-spn-pw)
          ARM_TENANT_ID: $(landscape-tenant)
          ARM_SUBSCRIPTION_ID: $(landscape-subscription)
